language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r dev-requirements.txt
script:
  - nosetests --with-cov --cover-erase --cover-html scalyr_agent/tests/ --verbose --with-xunit --xunit-file xunit.xml --ignore-files=.*log_processing_test.*