language: python
os:
  - linux
  - osx
python:
  - "2.4"
cache: pip
install:
  - pip install -r dev-requirements.txt
script:
  - nosetests --with-cov --cover-erase --cover-html scalyr_agent/tests/ --verbose --with-xunit --xunit-file xunit.xml --ignore-files=.*log_processing_test.*

# Add a dummy comment 3